const sampleProducts = [
  {
    name: "Portable Bluetooth Speaker",
    description: "Compact and powerful Bluetooth speaker for on-the-go music",
    categories: ["Electronics", "Audio"],
    brand: "SoundBeats",
    price: 79.99,
    discount: 10,
    stock_quantity: 90,
    productImages: ["url14", "url15"],
    averageRating: 4.5,
  },
  {
    name: "Leather Handbag",
    description: "Stylish leather handbag for fashion-forward individuals",
    categories: ["Fashion", "Accessories"],
    brand: "ChicStyle",
    price: 129.99,
    stock_quantity: 60,
    discount: 5,
    productImages: ["url16", "url17"],
    averageRating: 4.8,
  },
  {
    name: "Running Shoes",
    description: "Lightweight and durable shoes for running enthusiasts",
    categories: ["Clothing", "Shoes", "Sports"],
    brand: "FitGear",
    price: 79.99,
    discount: 8,
    stock_quantity: 120,

    productImages: ["url8", "url9"],

    averageRating: 4.7,
  },
  {
    name: "Professional Camera",
    description:
      "High-resolution professional camera for photography enthusiasts",
    categories: ["Electronics", "Photography"],
    brand: "SnapShot",
    price: 1899.99,
    stock_quantity: 30,
    discount: 200,
    productImages: ["url11", "url12"],
    averageRating: 4.6,
  },
  {
    name: "Men's Formal Shirt",
    description: "Classic formal shirt for men",
    categories: ["Clothing", "Men's Fashion"],
    brand: "FashionCo",
    price: 49.99,
    discount: 2,
    stock_quantity: 100,
    productImages: ["url4", "url5"],
    averageRating: 4.5,
  },
  {
    name: "Smartphone X",
    description: "High-end smartphone with advanced features",
    categories: ["Electronics", "Technology"],
    brand: "BrandX",
    price: 899.99,
    discount: 400,
    stock_quantity: 50,
    productImages: ["url1", "url2"],
    averageRating: 4.8,
  },
];
